# Generated by Django 3.2.4 on 2021-11-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('subscription', '0002_alter_subscription_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('BKASH', 'BKASH'), ('ROCKET', 'ROCKET'), ('CARD', 'CARD'), ('CASHON', 'CASHON'), ('SSLCOMMERZ', 'SSLCOMMERZ')], max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment is pending'), ('PAID', 'Payment received'), ('PARTIAL', 'Partial payment received'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=70, null=True)),
                ('is_failed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentDetails', to='user_profile.customerprofile')),
            ],
        ),
    ]
